
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;



import javax.swing.JToggleButton;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author shay quinn
 */
public class Air extends javax.swing.JFrame {

    public Air() {
        initComponents();
    }
    public static ArrayList<JToggleButton> compList = new ArrayList<>();
    private JToggleButton comp;
    private JToggleButton jt;
    
    public JToggleButton getComp() {
        return comp;
    }
    public void setComp(JToggleButton inComp) {
        comp = inComp;
    }
    public JToggleButton getJt() {
        return jt;
    }
    public void setJt(JToggleButton inJt) {
        jt = inJt;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Name = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Address = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Number = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jButton2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jToggleButton4 = new javax.swing.JToggleButton();
        jToggleButton5 = new javax.swing.JToggleButton();
        jToggleButton6 = new javax.swing.JToggleButton();
        jToggleButton7 = new javax.swing.JToggleButton();
        jToggleButton8 = new javax.swing.JToggleButton();
        jToggleButton9 = new javax.swing.JToggleButton();
        jToggleButton10 = new javax.swing.JToggleButton();
        jToggleButton11 = new javax.swing.JToggleButton();
        jToggleButton12 = new javax.swing.JToggleButton();
        jToggleButton13 = new javax.swing.JToggleButton();
        jToggleButton14 = new javax.swing.JToggleButton();
        jToggleButton15 = new javax.swing.JToggleButton();
        jToggleButton16 = new javax.swing.JToggleButton();
        jToggleButton17 = new javax.swing.JToggleButton();
        jToggleButton18 = new javax.swing.JToggleButton();
        jToggleButton19 = new javax.swing.JToggleButton();
        jToggleButton20 = new javax.swing.JToggleButton();
        jToggleButton21 = new javax.swing.JToggleButton();
        jToggleButton22 = new javax.swing.JToggleButton();
        jToggleButton23 = new javax.swing.JToggleButton();
        jToggleButton24 = new javax.swing.JToggleButton();
        jToggleButton25 = new javax.swing.JToggleButton();
        jToggleButton26 = new javax.swing.JToggleButton();
        jToggleButton27 = new javax.swing.JToggleButton();
        jToggleButton28 = new javax.swing.JToggleButton();
        jToggleButton29 = new javax.swing.JToggleButton();
        jToggleButton30 = new javax.swing.JToggleButton();
        jToggleButton31 = new javax.swing.JToggleButton();
        jToggleButton32 = new javax.swing.JToggleButton();
        jToggleButton33 = new javax.swing.JToggleButton();
        jToggleButton34 = new javax.swing.JToggleButton();
        jToggleButton35 = new javax.swing.JToggleButton();
        jToggleButton36 = new javax.swing.JToggleButton();
        jToggleButton37 = new javax.swing.JToggleButton();
        jToggleButton38 = new javax.swing.JToggleButton();
        jToggleButton39 = new javax.swing.JToggleButton();
        jToggleButton40 = new javax.swing.JToggleButton();
        jToggleButton41 = new javax.swing.JToggleButton();
        jToggleButton42 = new javax.swing.JToggleButton();
        jToggleButton43 = new javax.swing.JToggleButton();
        jToggleButton44 = new javax.swing.JToggleButton();
        jToggleButton45 = new javax.swing.JToggleButton();
        jToggleButton46 = new javax.swing.JToggleButton();
        jToggleButton47 = new javax.swing.JToggleButton();
        jToggleButton48 = new javax.swing.JToggleButton();
        jToggleButton49 = new javax.swing.JToggleButton();
        jToggleButton50 = new javax.swing.JToggleButton();
        jToggleButton51 = new javax.swing.JToggleButton();
        jToggleButton52 = new javax.swing.JToggleButton();
        jToggleButton53 = new javax.swing.JToggleButton();
        jToggleButton54 = new javax.swing.JToggleButton();
        jToggleButton55 = new javax.swing.JToggleButton();
        jToggleButton56 = new javax.swing.JToggleButton();
        jToggleButton57 = new javax.swing.JToggleButton();
        jToggleButton58 = new javax.swing.JToggleButton();
        jToggleButton59 = new javax.swing.JToggleButton();
        jToggleButton60 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Euphemia", 1, 14)); // NOI18N
        jLabel1.setText("Name");

        jLabel2.setFont(new java.awt.Font("Euphemia", 1, 14)); // NOI18N
        jLabel2.setText("Adress");

        jLabel3.setFont(new java.awt.Font("Euphemia", 1, 14)); // NOI18N
        jLabel3.setText("Number");

        jLabel4.setFont(new java.awt.Font("Myriad Pro Light", 2, 48)); // NOI18N
        jLabel4.setText("  Air.");

        jButton1.setFont(new java.awt.Font("Euphemia", 1, 14)); // NOI18N
        jButton1.setText("Clear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Address)
                            .addComponent(Number)
                            .addComponent(Name, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap())
        );

        jCheckBox1.setFont(new java.awt.Font("Euphemia", 1, 14)); // NOI18N
        jCheckBox1.setText("Paid");

        jButton2.setFont(new java.awt.Font("Euphemia", 1, 14)); // NOI18N
        jButton2.setText("Save");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(jCheckBox1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addContainerGap())
        );

        bg.add(jToggleButton1);
        jToggleButton1.setFont(new java.awt.Font("Euphemia", 0, 11)); // NOI18N
        jToggleButton1.setText("1a");
        jToggleButton1.addActionListener(al);
        jToggleButton1.setActionCommand("1");
        jToggleButton1.setName("1"); // NOI18N

        bg.add(jToggleButton2);
        jToggleButton2.setFont(new java.awt.Font("Euphemia", 0, 11)); // NOI18N
        jToggleButton2.setText("1b");
        jToggleButton2.addActionListener(al);
        jToggleButton2.setActionCommand("2");
        jToggleButton2.setName("2"); // NOI18N

        bg.add(jToggleButton3);
        jToggleButton3.setFont(new java.awt.Font("Euphemia", 0, 11)); // NOI18N
        jToggleButton3.setText("1c");
        jToggleButton3.addActionListener(al);
        jToggleButton3.setActionCommand("3");
        jToggleButton3.setName("3"); // NOI18N

        bg.add(jToggleButton4);
        jToggleButton4.setFont(new java.awt.Font("Euphemia", 0, 11)); // NOI18N
        jToggleButton4.setText("1d");
        jToggleButton4.addActionListener(al);
        jToggleButton4.setActionCommand("4");
        jToggleButton4.setName("4"); // NOI18N

        bg.add(jToggleButton5);
        jToggleButton5.setFont(new java.awt.Font("Euphemia", 0, 11)); // NOI18N
        jToggleButton5.setText("1e");
        jToggleButton5.addActionListener(al);
        jToggleButton5.setActionCommand("5");
        jToggleButton5.setName("5"); // NOI18N

        bg.add(jToggleButton6);
        jToggleButton6.setFont(new java.awt.Font("Euphemia", 0, 11)); // NOI18N
        jToggleButton6.setText("1f");
        jToggleButton6.addActionListener(al);
        jToggleButton6.setActionCommand("6");
        jToggleButton6.setName("6"); // NOI18N

        bg.add(jToggleButton7);
        jToggleButton7.setFont(new java.awt.Font("Euphemia", 0, 11)); // NOI18N
        jToggleButton7.setText("2a");
        jToggleButton7.addActionListener(al);
        jToggleButton7.setActionCommand("7");

        bg.add(jToggleButton8);
        jToggleButton8.setFont(new java.awt.Font("Euphemia", 0, 11)); // NOI18N
        jToggleButton8.setText("2b");
        jToggleButton8.addActionListener(al);
        jToggleButton8.setActionCommand("8");
        jToggleButton8.setName("8"); // NOI18N

        bg.add(jToggleButton9);
        jToggleButton9.setFont(new java.awt.Font("Euphemia", 0, 11)); // NOI18N
        jToggleButton9.setText("2c");
        jToggleButton9.addActionListener(al);
        jToggleButton9.setActionCommand("9");
        jToggleButton9.setName("9"); // NOI18N

        bg.add(jToggleButton10);
        jToggleButton10.setFont(new java.awt.Font("Euphemia", 0, 11)); // NOI18N
        jToggleButton10.setText("2d");
        jToggleButton10.addActionListener(al);
        jToggleButton10.setActionCommand("10");
        jToggleButton10.setName("10"); // NOI18N

        bg.add(jToggleButton11);
        jToggleButton11.setFont(new java.awt.Font("Euphemia", 0, 11)); // NOI18N
        jToggleButton11.setText("2e");
        jToggleButton11.addActionListener(al);
        jToggleButton11.setActionCommand("11");
        jToggleButton11.setName("11"); // NOI18N

        bg.add(jToggleButton12);
        jToggleButton12.setFont(new java.awt.Font("Euphemia", 0, 11)); // NOI18N
        jToggleButton12.setText("2f");
        jToggleButton12.addActionListener(al);
        jToggleButton12.setActionCommand("12");
        jToggleButton12.setName("12"); // NOI18N

        bg.add(jToggleButton13);
        jToggleButton13.setFont(new java.awt.Font("Euphemia", 0, 11)); // NOI18N
        jToggleButton13.setText("3a");
        jToggleButton13.addActionListener(al);
        jToggleButton13.setActionCommand("13");
        jToggleButton13.setName("13"); // NOI18N

        bg.add(jToggleButton14);
        jToggleButton14.setFont(new java.awt.Font("Euphemia", 0, 11)); // NOI18N
        jToggleButton14.setText("3b");
        jToggleButton14.addActionListener(al);
        jToggleButton14.setActionCommand("14");
        jToggleButton14.setName("14"); // NOI18N

        bg.add(jToggleButton15);
        jToggleButton15.setFont(new java.awt.Font("Euphemia", 0, 11)); // NOI18N
        jToggleButton15.setText("3c");
        jToggleButton15.addActionListener(al);
        jToggleButton15.setActionCommand("15");
        jToggleButton15.setName("15"); // NOI18N

        bg.add(jToggleButton16);
        jToggleButton16.setFont(new java.awt.Font("Euphemia", 0, 11)); // NOI18N
        jToggleButton16.setText("3d");
        jToggleButton16.addActionListener(al);
        jToggleButton16.setActionCommand("16");
        jToggleButton16.setName("16"); // NOI18N

        bg.add(jToggleButton17);
        jToggleButton17.setFont(new java.awt.Font("Euphemia", 0, 11)); // NOI18N
        jToggleButton17.setText("3e");
        jToggleButton17.addActionListener(al);
        jToggleButton17.setActionCommand("17");
        jToggleButton17.setName("17"); // NOI18N

        bg.add(jToggleButton18);
        jToggleButton18.setFont(new java.awt.Font("Euphemia", 0, 11)); // NOI18N
        jToggleButton18.setText("3f");
        jToggleButton18.addActionListener(al);
        jToggleButton18.setActionCommand("18");
        jToggleButton18.setName("18"); // NOI18N

        bg.add(jToggleButton19);
        jToggleButton19.setFont(new java.awt.Font("Euphemia", 0, 11)); // NOI18N
        jToggleButton19.setText("4a");
        jToggleButton19.addActionListener(al);
        jToggleButton19.setActionCommand("19");
        jToggleButton19.setName("19"); // NOI18N

        bg.add(jToggleButton20);
        jToggleButton20.setFont(new java.awt.Font("Euphemia", 0, 11)); // NOI18N
        jToggleButton20.setText("4b");
        jToggleButton20.addActionListener(al);
        jToggleButton20.setActionCommand("20");
        jToggleButton20.setName("20"); // NOI18N

        bg.add(jToggleButton21);
        jToggleButton21.setFont(new java.awt.Font("Euphemia", 0, 11)); // NOI18N
        jToggleButton21.setText("4c");
        jToggleButton21.addActionListener(al);
        jToggleButton21.setActionCommand("21");
        jToggleButton21.setName("21"); // NOI18N

        bg.add(jToggleButton22);
        jToggleButton22.setFont(new java.awt.Font("Euphemia", 0, 11)); // NOI18N
        jToggleButton22.setText("4d");
        jToggleButton22.addActionListener(al);
        jToggleButton22.setActionCommand("22");
        jToggleButton22.setName("22"); // NOI18N

        bg.add(jToggleButton23);
        jToggleButton23.setFont(new java.awt.Font("Euphemia", 0, 11)); // NOI18N
        jToggleButton23.setText("4e");
        jToggleButton23.addActionListener(al);
        jToggleButton23.setActionCommand("23");
        jToggleButton23.setName("23"); // NOI18N

        bg.add(jToggleButton24);
        jToggleButton24.setFont(new java.awt.Font("Euphemia", 0, 11)); // NOI18N
        jToggleButton24.setText("4f");
        jToggleButton24.addActionListener(al);
        jToggleButton24.setActionCommand("24");
        jToggleButton24.setName("24"); // NOI18N

        bg.add(jToggleButton25);
        jToggleButton25.setFont(new java.awt.Font("Euphemia", 0, 11)); // NOI18N
        jToggleButton25.setText("5a");
        jToggleButton25.addActionListener(al);
        jToggleButton25.setActionCommand("25");
        jToggleButton25.setName("25"); // NOI18N

        bg.add(jToggleButton26);
        jToggleButton26.setFont(new java.awt.Font("Euphemia", 0, 11)); // NOI18N
        jToggleButton26.setText("5b");
        jToggleButton26.addActionListener(al);
        jToggleButton26.setActionCommand("26");
        jToggleButton26.setName("26"); // NOI18N

        bg.add(jToggleButton27);
        jToggleButton27.setFont(new java.awt.Font("Euphemia", 0, 11)); // NOI18N
        jToggleButton27.setText("5c");
        jToggleButton27.addActionListener(al);
        jToggleButton27.setActionCommand("27");
        jToggleButton27.setName("27"); // NOI18N

        bg.add(jToggleButton28);
        jToggleButton28.setFont(new java.awt.Font("Euphemia", 0, 11)); // NOI18N
        jToggleButton28.setText("5d");
        jToggleButton28.addActionListener(al);
        jToggleButton28.setActionCommand("28");
        jToggleButton28.setName("28"); // NOI18N

        bg.add(jToggleButton29);
        jToggleButton29.setFont(new java.awt.Font("Euphemia", 0, 11)); // NOI18N
        jToggleButton29.setText("5e");
        jToggleButton29.addActionListener(al);
        jToggleButton29.setActionCommand("29");
        jToggleButton29.setName("29"); // NOI18N

        bg.add(jToggleButton30);
        jToggleButton30.setFont(new java.awt.Font("Euphemia", 0, 11)); // NOI18N
        jToggleButton30.setText("5f");
        jToggleButton30.addActionListener(al);
        jToggleButton30.setActionCommand("30");
        jToggleButton30.setName("30"); // NOI18N

        bg.add(jToggleButton31);
        jToggleButton31.setFont(new java.awt.Font("Euphemia", 0, 11)); // NOI18N
        jToggleButton31.setText("6a");
        jToggleButton31.addActionListener(al);
        jToggleButton31.setActionCommand("31");
        jToggleButton31.setName("31"); // NOI18N

        bg.add(jToggleButton32);
        jToggleButton32.setFont(new java.awt.Font("Euphemia", 0, 11)); // NOI18N
        jToggleButton32.setText("6b");
        jToggleButton32.addActionListener(al);
        jToggleButton32.setActionCommand("32");
        jToggleButton32.setName("32"); // NOI18N

        bg.add(jToggleButton33);
        jToggleButton33.setFont(new java.awt.Font("Euphemia", 0, 11)); // NOI18N
        jToggleButton33.setText("6c");
        jToggleButton33.addActionListener(al);
        jToggleButton33.setActionCommand("33");
        jToggleButton33.setName("33"); // NOI18N

        bg.add(jToggleButton34);
        jToggleButton34.setFont(new java.awt.Font("Euphemia", 0, 11)); // NOI18N
        jToggleButton34.setText("6d");
        jToggleButton34.addActionListener(al);
        jToggleButton34.setActionCommand("34");
        jToggleButton34.setName("34"); // NOI18N

        bg.add(jToggleButton35);
        jToggleButton35.setFont(new java.awt.Font("Euphemia", 0, 11)); // NOI18N
        jToggleButton35.setText("6e");
        jToggleButton35.addActionListener(al);
        jToggleButton35.setActionCommand("35");
        jToggleButton35.setName("35"); // NOI18N

        bg.add(jToggleButton36);
        jToggleButton36.setFont(new java.awt.Font("Euphemia", 0, 11)); // NOI18N
        jToggleButton36.setText("6f");
        jToggleButton36.addActionListener(al);
        jToggleButton36.setActionCommand("36");
        jToggleButton36.setName("36"); // NOI18N

        bg.add(jToggleButton37);
        jToggleButton37.setFont(new java.awt.Font("Euphemia", 0, 11)); // NOI18N
        jToggleButton37.setText("7a");
        jToggleButton37.addActionListener(al);
        jToggleButton37.setActionCommand("37");
        jToggleButton37.setName("37"); // NOI18N

        bg.add(jToggleButton38);
        jToggleButton38.setFont(new java.awt.Font("Euphemia", 0, 11)); // NOI18N
        jToggleButton38.setText("7b");
        jToggleButton38.addActionListener(al);
        jToggleButton38.setActionCommand("38");
        jToggleButton38.setName("38"); // NOI18N

        bg.add(jToggleButton39);
        jToggleButton39.setFont(new java.awt.Font("Euphemia", 0, 11)); // NOI18N
        jToggleButton39.setText("7c");
        jToggleButton39.addActionListener(al);
        jToggleButton39.setActionCommand("39");
        jToggleButton39.setName("39"); // NOI18N

        bg.add(jToggleButton40);
        jToggleButton40.setFont(new java.awt.Font("Euphemia", 0, 11)); // NOI18N
        jToggleButton40.setText("7d");
        jToggleButton40.addActionListener(al);
        jToggleButton40.setActionCommand("40");
        jToggleButton40.setName("40"); // NOI18N

        bg.add(jToggleButton41);
        jToggleButton41.setFont(new java.awt.Font("Euphemia", 0, 11)); // NOI18N
        jToggleButton41.setText("7e");
        jToggleButton41.addActionListener(al);
        jToggleButton41.setActionCommand("41");
        jToggleButton41.setName("41"); // NOI18N

        bg.add(jToggleButton42);
        jToggleButton42.setFont(new java.awt.Font("Euphemia", 0, 11)); // NOI18N
        jToggleButton42.setText("7f");
        jToggleButton42.addActionListener(al);
        jToggleButton42.setActionCommand("42");
        jToggleButton42.setName("42"); // NOI18N

        bg.add(jToggleButton43);
        jToggleButton43.setFont(new java.awt.Font("Euphemia", 0, 11)); // NOI18N
        jToggleButton43.setText("8a");
        jToggleButton43.addActionListener(al);
        jToggleButton43.setActionCommand("43");
        jToggleButton43.setName("43"); // NOI18N

        bg.add(jToggleButton44);
        jToggleButton44.setFont(new java.awt.Font("Euphemia", 0, 11)); // NOI18N
        jToggleButton44.setText(" 8b");
        jToggleButton44.addActionListener(al);
        jToggleButton44.setActionCommand("44");
        jToggleButton44.setName("44"); // NOI18N

        bg.add(jToggleButton45);
        jToggleButton45.setFont(new java.awt.Font("Euphemia", 0, 11)); // NOI18N
        jToggleButton45.setText("8c");
        jToggleButton45.addActionListener(al);
        jToggleButton45.setActionCommand("45");
        jToggleButton45.setName("45"); // NOI18N

        bg.add(jToggleButton46);
        jToggleButton46.setFont(new java.awt.Font("Euphemia", 0, 11)); // NOI18N
        jToggleButton46.setText("8d");
        jToggleButton46.addActionListener(al);
        jToggleButton46.setActionCommand("46");
        jToggleButton46.setName("46"); // NOI18N

        bg.add(jToggleButton47);
        jToggleButton47.setFont(new java.awt.Font("Euphemia", 0, 11)); // NOI18N
        jToggleButton47.setText("8e");
        jToggleButton47.addActionListener(al);
        jToggleButton47.setActionCommand("47");
        jToggleButton47.setName("47"); // NOI18N

        bg.add(jToggleButton48);
        jToggleButton48.setFont(new java.awt.Font("Euphemia", 0, 11)); // NOI18N
        jToggleButton48.setText("8f");
        jToggleButton48.addActionListener(al);
        jToggleButton48.setActionCommand("48");
        jToggleButton48.setName("48"); // NOI18N

        bg.add(jToggleButton49);
        jToggleButton49.setFont(new java.awt.Font("Euphemia", 0, 11)); // NOI18N
        jToggleButton49.setText("9a");
        jToggleButton49.addActionListener(al);
        jToggleButton49.setActionCommand("49");
        jToggleButton49.setName("49"); // NOI18N

        bg.add(jToggleButton50);
        jToggleButton50.setFont(new java.awt.Font("Euphemia", 0, 11)); // NOI18N
        jToggleButton50.setText("9b");
        jToggleButton50.addActionListener(al);
        jToggleButton50.setActionCommand("50");
        jToggleButton50.setName("50"); // NOI18N

        bg.add(jToggleButton51);
        jToggleButton51.setFont(new java.awt.Font("Euphemia", 0, 11)); // NOI18N
        jToggleButton51.setText("9c");
        jToggleButton51.addActionListener(al);
        jToggleButton51.setActionCommand("51");
        jToggleButton51.setName("51"); // NOI18N

        bg.add(jToggleButton52);
        jToggleButton52.setFont(new java.awt.Font("Euphemia", 0, 11)); // NOI18N
        jToggleButton52.setText("9d");
        jToggleButton52.addActionListener(al);
        jToggleButton52.setActionCommand("52");
        jToggleButton52.setName("52"); // NOI18N

        bg.add(jToggleButton53);
        jToggleButton53.setFont(new java.awt.Font("Euphemia", 0, 11)); // NOI18N
        jToggleButton53.setText("9e");
        jToggleButton53.addActionListener(al);
        jToggleButton53.setActionCommand("53");
        jToggleButton53.setName("53"); // NOI18N

        bg.add(jToggleButton54);
        jToggleButton54.setFont(new java.awt.Font("Euphemia", 0, 11)); // NOI18N
        jToggleButton54.setText("9f");
        jToggleButton54.addActionListener(al);
        jToggleButton54.setActionCommand("54");
        jToggleButton54.setName("54"); // NOI18N

        bg.add(jToggleButton55);
        jToggleButton55.setFont(new java.awt.Font("Euphemia", 0, 11)); // NOI18N
        jToggleButton55.setText("10a");
        jToggleButton55.addActionListener(al);
        jToggleButton55.setActionCommand("55");
        jToggleButton55.setName("55"); // NOI18N

        bg.add(jToggleButton56);
        jToggleButton56.setFont(new java.awt.Font("Euphemia", 0, 11)); // NOI18N
        jToggleButton56.setText("10b");
        jToggleButton56.addActionListener(al);
        jToggleButton56.setActionCommand("56");
        jToggleButton56.setName("56"); // NOI18N

        bg.add(jToggleButton57);
        jToggleButton57.setFont(new java.awt.Font("Euphemia", 0, 11)); // NOI18N
        jToggleButton57.setText("10c");
        jToggleButton57.addActionListener(al);
        jToggleButton57.setActionCommand("57");
        jToggleButton57.setName("57"); // NOI18N

        bg.add(jToggleButton58);
        jToggleButton58.setFont(new java.awt.Font("Euphemia", 0, 11)); // NOI18N
        jToggleButton58.setText("10d");
        jToggleButton58.addActionListener(al);
        jToggleButton58.setActionCommand("58");
        jToggleButton58.setName("58"); // NOI18N

        bg.add(jToggleButton59);
        jToggleButton59.setFont(new java.awt.Font("Euphemia", 0, 11)); // NOI18N
        jToggleButton59.setText("10e");
        jToggleButton59.addActionListener(al);
        jToggleButton59.setActionCommand("59");
        jToggleButton59.setName("59"); // NOI18N
        /*
        jToggleButton59.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton59ActionPerformed(evt);
            }
        });
        */

        bg.add(jToggleButton60);
        jToggleButton60.setFont(new java.awt.Font("Euphemia", 0, 11)); // NOI18N
        jToggleButton60.setText("10f");
        jToggleButton60.addActionListener(al);
        jToggleButton60.setActionCommand("60");
        jToggleButton60.setName("60"); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jToggleButton55, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton56, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton57)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton58, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton59, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton60, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jToggleButton7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jToggleButton49)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton50, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton51, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton52, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton53, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton54, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jToggleButton43, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton44, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton45, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton46)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton47, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton48, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jToggleButton37, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton38, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton39, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton40, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton41)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton42, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jToggleButton31)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton32, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton33, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton34, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton35, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton36, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jToggleButton25, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton27, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton28, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton29, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton30, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jToggleButton13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jToggleButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton21, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton22, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton24, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jToggleButton1, jToggleButton10, jToggleButton11, jToggleButton12, jToggleButton13, jToggleButton14, jToggleButton15, jToggleButton16, jToggleButton17, jToggleButton18, jToggleButton19, jToggleButton2, jToggleButton20, jToggleButton21, jToggleButton22, jToggleButton23, jToggleButton24, jToggleButton25, jToggleButton26, jToggleButton27, jToggleButton28, jToggleButton29, jToggleButton3, jToggleButton30, jToggleButton31, jToggleButton32, jToggleButton33, jToggleButton34, jToggleButton35, jToggleButton36, jToggleButton37, jToggleButton38, jToggleButton39, jToggleButton4, jToggleButton40, jToggleButton41, jToggleButton42, jToggleButton43, jToggleButton44, jToggleButton45, jToggleButton46, jToggleButton47, jToggleButton48, jToggleButton49, jToggleButton5, jToggleButton50, jToggleButton51, jToggleButton52, jToggleButton53, jToggleButton54, jToggleButton55, jToggleButton56, jToggleButton57, jToggleButton58, jToggleButton59, jToggleButton6, jToggleButton60, jToggleButton7, jToggleButton8, jToggleButton9});

        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton2)
                    .addComponent(jToggleButton3)
                    .addComponent(jToggleButton4)
                    .addComponent(jToggleButton5)
                    .addComponent(jToggleButton6)
                    .addComponent(jToggleButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton7)
                    .addComponent(jToggleButton8)
                    .addComponent(jToggleButton9)
                    .addComponent(jToggleButton10)
                    .addComponent(jToggleButton11)
                    .addComponent(jToggleButton12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton13)
                    .addComponent(jToggleButton14)
                    .addComponent(jToggleButton15)
                    .addComponent(jToggleButton16)
                    .addComponent(jToggleButton17)
                    .addComponent(jToggleButton18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton19)
                    .addComponent(jToggleButton20)
                    .addComponent(jToggleButton21)
                    .addComponent(jToggleButton22)
                    .addComponent(jToggleButton23)
                    .addComponent(jToggleButton24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton25)
                    .addComponent(jToggleButton26)
                    .addComponent(jToggleButton27)
                    .addComponent(jToggleButton28)
                    .addComponent(jToggleButton29)
                    .addComponent(jToggleButton30))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton31)
                    .addComponent(jToggleButton32)
                    .addComponent(jToggleButton33)
                    .addComponent(jToggleButton34)
                    .addComponent(jToggleButton35)
                    .addComponent(jToggleButton36))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton37)
                    .addComponent(jToggleButton38)
                    .addComponent(jToggleButton39)
                    .addComponent(jToggleButton40)
                    .addComponent(jToggleButton41)
                    .addComponent(jToggleButton42))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton43)
                    .addComponent(jToggleButton44)
                    .addComponent(jToggleButton45)
                    .addComponent(jToggleButton46)
                    .addComponent(jToggleButton47)
                    .addComponent(jToggleButton48))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton49)
                    .addComponent(jToggleButton50)
                    .addComponent(jToggleButton51)
                    .addComponent(jToggleButton52)
                    .addComponent(jToggleButton53)
                    .addComponent(jToggleButton54))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton55)
                    .addComponent(jToggleButton56)
                    .addComponent(jToggleButton57)
                    .addComponent(jToggleButton58)
                    .addComponent(jToggleButton59)
                    .addComponent(jToggleButton60))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jToggleButton1, jToggleButton10, jToggleButton11, jToggleButton12, jToggleButton13, jToggleButton14, jToggleButton15, jToggleButton16, jToggleButton17, jToggleButton18, jToggleButton19, jToggleButton2, jToggleButton20, jToggleButton21, jToggleButton22, jToggleButton23, jToggleButton24, jToggleButton25, jToggleButton26, jToggleButton27, jToggleButton28, jToggleButton29, jToggleButton3, jToggleButton30, jToggleButton31, jToggleButton32, jToggleButton33, jToggleButton34, jToggleButton35, jToggleButton36, jToggleButton37, jToggleButton38, jToggleButton39, jToggleButton4, jToggleButton40, jToggleButton41, jToggleButton42, jToggleButton43, jToggleButton44, jToggleButton45, jToggleButton46, jToggleButton47, jToggleButton48, jToggleButton49, jToggleButton5, jToggleButton50, jToggleButton51, jToggleButton52, jToggleButton53, jToggleButton54, jToggleButton55, jToggleButton56, jToggleButton57, jToggleButton58, jToggleButton59, jToggleButton6, jToggleButton60, jToggleButton7, jToggleButton8, jToggleButton9});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int key = 1;
        try {
            getConnectiion(key);
        } catch (NumberFormatException e) {
            System.out.println("1 Error :" + e);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jToggleButton59ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton59ActionPerformed

    }//GEN-LAST:event_jToggleButton59ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            int key = 0;
            getConnectiion(key);
        } catch (Exception e) {
            System.out.println("2 Error : " + e);
        }
    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
                   try {
            int key = 2;
                if("clear".equals(Name.getText().trim())){            
                Component[] component = jPanel4.getComponents();
                for (Component component1 : component) {
                    JToggleButton jt2 = (JToggleButton) component1;
                    if(jt2.isEnabled()==false){
                        jt2.setEnabled(true);
                    }
                } 
                getConnectiion(key);
                Air.compList.clear();
                bg.clearSelection();
            }else{
                bg.clearSelection();
                Name.setText("");
                Address.setText("");
                Number.setText("");
            } 
        } catch (Exception e) {
            System.out.println("3 Error : " + e);
        }
        } catch (Exception e) {
            System.out.println("3 Error : " + e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    ActionListener al = (ActionEvent ae) -> {
        JToggleButton button = (JToggleButton) ae.getSource();
        // System.out.println("getUIClassID "+button.getUIClassID());
        //System.out.println("Location" + button);
        setComp(button);
    };
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Air.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Air().setVisible(true);
            }
            private void getConnectiion() throws Exception {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Address;
    private javax.swing.JTextField Name;
    private javax.swing.JTextField Number;
    private javax.swing.ButtonGroup bg;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton10;
    private javax.swing.JToggleButton jToggleButton11;
    private javax.swing.JToggleButton jToggleButton12;
    private javax.swing.JToggleButton jToggleButton13;
    private javax.swing.JToggleButton jToggleButton14;
    private javax.swing.JToggleButton jToggleButton15;
    private javax.swing.JToggleButton jToggleButton16;
    private javax.swing.JToggleButton jToggleButton17;
    private javax.swing.JToggleButton jToggleButton18;
    private javax.swing.JToggleButton jToggleButton19;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton20;
    private javax.swing.JToggleButton jToggleButton21;
    private javax.swing.JToggleButton jToggleButton22;
    private javax.swing.JToggleButton jToggleButton23;
    private javax.swing.JToggleButton jToggleButton24;
    private javax.swing.JToggleButton jToggleButton25;
    private javax.swing.JToggleButton jToggleButton26;
    private javax.swing.JToggleButton jToggleButton27;
    private javax.swing.JToggleButton jToggleButton28;
    private javax.swing.JToggleButton jToggleButton29;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton30;
    private javax.swing.JToggleButton jToggleButton31;
    private javax.swing.JToggleButton jToggleButton32;
    private javax.swing.JToggleButton jToggleButton33;
    private javax.swing.JToggleButton jToggleButton34;
    private javax.swing.JToggleButton jToggleButton35;
    private javax.swing.JToggleButton jToggleButton36;
    private javax.swing.JToggleButton jToggleButton37;
    private javax.swing.JToggleButton jToggleButton38;
    private javax.swing.JToggleButton jToggleButton39;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JToggleButton jToggleButton40;
    private javax.swing.JToggleButton jToggleButton41;
    private javax.swing.JToggleButton jToggleButton42;
    private javax.swing.JToggleButton jToggleButton43;
    private javax.swing.JToggleButton jToggleButton44;
    private javax.swing.JToggleButton jToggleButton45;
    private javax.swing.JToggleButton jToggleButton46;
    private javax.swing.JToggleButton jToggleButton47;
    private javax.swing.JToggleButton jToggleButton48;
    private javax.swing.JToggleButton jToggleButton49;
    private javax.swing.JToggleButton jToggleButton5;
    private javax.swing.JToggleButton jToggleButton50;
    private javax.swing.JToggleButton jToggleButton51;
    private javax.swing.JToggleButton jToggleButton52;
    private javax.swing.JToggleButton jToggleButton53;
    private javax.swing.JToggleButton jToggleButton54;
    private javax.swing.JToggleButton jToggleButton55;
    private javax.swing.JToggleButton jToggleButton56;
    private javax.swing.JToggleButton jToggleButton57;
    private javax.swing.JToggleButton jToggleButton58;
    private javax.swing.JToggleButton jToggleButton59;
    private javax.swing.JToggleButton jToggleButton6;
    private javax.swing.JToggleButton jToggleButton60;
    private javax.swing.JToggleButton jToggleButton7;
    private javax.swing.JToggleButton jToggleButton8;
    private javax.swing.JToggleButton jToggleButton9;
    // End of variables declaration//GEN-END:variables

    private void getConnectiion(int key) {
        try {
            String driver = "com.mysql.jdbc.Driver";
            String url = "jdbc:mysql://localhost:3306/Air";
            String username = "root";
            String password = "3HURGC0QJLsIvBccLsbN";
            //Connection con = DriverManager.getConnection("jdbc:ucanaccess://C:\\Users\\squinnjava\\Desktop\\Week10\\Air.accdb");
            try (java.sql.Connection con = DriverManager.getConnection(url, username, password); //Connection con = DriverManager.getConnection("jdbc:ucanaccess://C:\\Users\\squinnjava\\Desktop\\Week10\\Air.accdb");
                    java.sql.Statement s = con.createStatement()) {
                // key 0 = read. key 1 = write. key 2 = delete
                String query;
                switch (key) {
                    case 0:
                        read(s);
                        break;
                    case 1:
                        write(s);
                        break;
                    case 2:
                        delete(s);
                        break;
                    default:
                        break;
                }
                s.close();
                con.close();
            }
        } catch (NumberFormatException | SQLException e) {
            System.out.println("4 Error :" + e);
        }
    }
    private void read(Statement s) throws SQLException {
        String set;
        String query = "SELECT Seat FROM air2.air2";
        ResultSet rs1 = s.executeQuery(query);
        ResultSetMetaData met = rs1.getMetaData();
        int colNum = met.getColumnCount();
        while (rs1.next()) {
            for (int i = 1; i <= colNum; i++) {
                set = rs1.getString(i);              
                System.out.println(set + ", has been read from the data base," + "connect : ");
                Component[] component = jPanel4.getComponents();
                int setInt = Integer.parseInt(set);
                JToggleButton jt1 = (JToggleButton) component[setInt];
                Air.compList.add(jt1);
                jt1.setEnabled(false);
            }
        }
    }
    private void write(Statement s) throws SQLException {
        String str;
        try {
            int seat = 0;
            JToggleButton jb = getComp();
            Air.compList.add(jb);
            Component[] component = jPanel4.getComponents();
            for (int i = 0; i < Air.compList.size(); i++) {
                for (int j = 0; j < component.length; j++) {
                    JToggleButton jt2 = (JToggleButton) component[j];
                    if (Air.compList.get(i) == jt2) {
                        setJt(jt2);
                        seat = j;
                    }
                }
            }
            str = bg.getSelection().getActionCommand();
            int id = Integer.parseInt(str);
            String name = Name.getText();
            String address = Address.getText();
            int number = Integer.parseInt(Number.getText());
            StringBuilder sb = new StringBuilder("");
            sb.append("INSERT INTO air2.air2");
            sb.append("(id, Name, Address, Number, Seat)");
            sb.append(" VALUES(");
            sb.append("'");
            sb.append(id);
            sb.append("','");
            sb.append(name);
            sb.append("','");
            sb.append(address);
            sb.append("','");
            sb.append(number);
            sb.append("','");
            StringBuilder append = sb.append(seat);
            sb.append("')");
            String outStr = sb.toString();
            s.execute(outStr);
            System.err.println("--------------------------------------------------------------");
            System.out.println("connect : " + id + ", " + name + ", " + address + ", " + number + ", " + seat + ", has been writen to the database,");           
            System.out.println("seat : " + seat);

            getJt().setEnabled(false);
            bg.clearSelection();
        } catch (NumberFormatException | SQLException e) {
            System.out.println("5 Error : " + e);
        }
        System.out.println("Air.compList count : " + Air.compList.size());
    }
       private void delete(Statement s) throws SQLException {
        System.err.println("--------------------------------------------------------------");
        System.err.println("connect : the data base has been deleted,");
        String query = "DELETE FROM air2.air2";
        s.executeUpdate(query);
    }
}
